# Generated by Django 2.0.5 on 2018-10-03 20:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reset_pass_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regn_no', models.IntegerField(validators=[django.core.validators.MinValueValidator(2011101000), django.core.validators.MaxValueValidator(2100107999)])),
                ('timestamp', models.DateField()),
            ],
        ),
    ]
