# Generated by Django 2.0.5 on 2018-10-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_reset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reset_pass_db',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
