# Generated by Django 2.0.5 on 2018-08-29 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180826_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='password_db',
            name='last_ip',
        ),
    ]
