# Generated by Django 2.0.5 on 2018-08-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_password_db_last_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel_db',
            name='hostel_name',
            field=models.CharField(choices=[('Patkai-A', 'Patkai-A'), ('Patkai-B', 'Patkai-B'), ('Patkai-C', 'Patkai-C'), ('Tiyi', 'Tiyi'), ('Duzukou', 'Duzukou'), ('Zanibu', 'Zanibu'), ('Saramati-A', 'Saramati-A'), ('Saramati-B', 'Saramati-B'), ('Saramati-C', 'Saramati-C'), ('New-Hostel', 'New-Hostel')], max_length=20, primary_key=True, serialize=False),
        ),
    ]
