# Generated by Django 2.0.5 on 2018-10-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180830_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_db',
            name='refund',
            field=models.IntegerField(default=0),
        ),
    ]
