# Generated by Django 2.0.5 on 2019-01-21 08:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_student_db_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel_db',
            name='hostel_name',
            field=models.CharField(choices=[('Japfu', 'Japfu'), ('Patkai-A', 'Patkai-A'), ('Patkai-B', 'Patkai-B'), ('Patkai-C', 'Patkai-C'), ('Tiyi', 'Tiyi'), ('Duzukou', 'Duzukou'), ('Zanibu', 'Zanibu'), ('Saramati-A', 'Saramati-A'), ('Saramati-B', 'Saramati-B'), ('Saramati-C', 'Saramati-C'), ('New-Hostel', 'New-Hostel')], max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student_db',
            name='regn_no',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(2012103001), django.core.validators.MaxValueValidator(2100107999)]),
        ),
    ]
