# Generated by Django 2.0.5 on 2019-01-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190121_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_db',
            name='room_no',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
