# Generated by Django 2.0.5 on 2019-01-28 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_student_db_room_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student_db',
            options={'verbose_name': 'Student Detail'},
        ),
    ]
