# Generated by Django 2.0.5 on 2019-01-28 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20190128_1746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostel_db',
            options={'verbose_name': 'Hostel Detail'},
        ),
        migrations.AlterModelOptions(
            name='warden_db',
            options={'verbose_name': 'Warden Detail'},
        ),
    ]
