# Generated by Django 2.0.5 on 2018-08-26 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaints_db',
            fields=[
                ('complaint_id', models.IntegerField(primary_key=True, serialize=False)),
                ('complaint_title', models.CharField(max_length=50)),
                ('complaint_date', models.DateField()),
                ('complaint_image', models.BinaryField()),
                ('complaint_status', models.BinaryField(default=None)),
                ('student_regn_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.student_db')),
            ],
        ),
    ]
