# Generated by Django 2.0.5 on 2018-08-26 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
    ]
