# Generated by Django 2.0.5 on 2018-08-26 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20180826_1523'),
    ]

    operations = [
    ]
