# Generated by Django 2.0.5 on 2018-08-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20180826_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints_db',
            name='complaint_status',
            field=models.BooleanField(default=False),
        ),
    ]
