# Generated by Django 2.0.5 on 2018-08-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20180826_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints_db',
            name='complaint_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
