# Generated by Django 2.0.5 on 2018-08-26 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20180826_1709'),
    ]

    operations = [
    ]
