# Generated by Django 2.0.5 on 2018-08-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20180826_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints_db',
            name='complaint_type',
            field=models.CharField(default=None, max_length=11),
            preserve_default=False,
        ),
    ]
