# Generated by Django 2.0.5 on 2018-08-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_complaints_db_complaint_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints_db',
            name='complaint_image',
            field=models.BinaryField(null=True),
        ),
    ]
