# Generated by Django 2.0.5 on 2018-08-26 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20180826_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaints_db',
            old_name='complaint_status',
            new_name='complaint_solved',
        ),
    ]
