# Generated by Django 2.0.5 on 2018-10-24 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180830_2339'),
        ('student', '0014_auto_20180826_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='application_db',
            fields=[
                ('app_id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=250)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('accepted', models.BinaryField(null=True)),
                ('declined', models.BinaryField(null=True)),
                ('reg_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.student_db')),
            ],
        ),
    ]
