# Generated by Django 2.0.5 on 2018-10-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_application_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application_db',
            name='accepted',
            field=models.BinaryField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='application_db',
            name='declined',
            field=models.BinaryField(default=False, null=True),
        ),
    ]
