# Generated by Django 2.0.5 on 2018-10-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_auto_20181028_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application_db',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application_db',
            name='declined',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application_db',
            name='reason',
            field=models.CharField(max_length=251),
        ),
    ]
