# Generated by Django 2.0.5 on 2019-01-28 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_auto_20190128_1755'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application_db',
            options={'verbose_name': 'Application Managment', 'verbose_name_plural': 'Applications Managment'},
        ),
    ]
