# Generated by Django 2.0.5 on 2019-01-27 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry_exit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry_table',
            name='in_date',
        ),
    ]
