# Generated by Django 2.0.5 on 2019-01-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry_exit', '0002_remove_entry_table_in_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry_table',
            name='is_complete',
        ),
        migrations.AddField(
            model_name='entry_table',
            name='in_date',
            field=models.DateTimeField(null=True),
        ),
    ]
