# Generated by Django 2.0.5 on 2019-01-27 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_student_db_room_no'),
        ('entry_exit', '0003_auto_20190127_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Still_Out',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_complete', models.BinaryField(default=False)),
                ('out_date', models.DateTimeField(auto_now=True)),
                ('in_date', models.DateTimeField(null=True)),
                ('reason', models.CharField(max_length=200)),
                ('regn_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.student_db')),
            ],
        ),
    ]
