# Generated by Django 2.0.5 on 2019-01-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry_exit', '0005_auto_20190127_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_still_out',
            name='out_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
