# Generated by Django 2.0.5 on 2019-01-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry_exit', '0007_auto_20190127_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry_exit',
            name='in_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='entry_exit',
            name='out_date',
            field=models.DateTimeField(),
        ),
    ]
