# Generated by Django 2.0.5 on 2019-01-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry_exit', '0008_auto_20190127_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_still_out',
            name='in_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
