# Generated by Django 2.0.5 on 2019-01-27 19:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry_exit', '0010_auto_20190127_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guard_Details',
            fields=[
                ('Employee_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Guard_Name', models.CharField(max_length=80)),
                ('Contact_No', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('Password', models.CharField(max_length=160)),
                ('Confirm_Password', models.CharField(default=None, max_length=160, null=True)),
            ],
        ),
    ]
