# Generated by Django 2.0.5 on 2019-01-27 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry_exit', '0011_guard_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Guard_Details',
            new_name='Guard_Detail',
        ),
    ]
