# Generated by Django 2.0.5 on 2019-01-28 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry_exit', '0012_auto_20190128_0039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry_exit',
            options={'verbose_name': 'Entry Exit Detail'},
        ),
        migrations.AlterModelOptions(
            name='guard_detail',
            options={'verbose_name': 'Guard Detail', 'verbose_name_plural': 'Guards Details'},
        ),
        migrations.AlterModelOptions(
            name='student_still_out',
            options={'verbose_name': 'Student Outside Campus', 'verbose_name_plural': 'Students Outside Campus'},
        ),
    ]
